### ISSUE TITLE
[review] baba-is-you-2

### ISSUE THREAD

**Issue by tomibennett** [archiloque/blog#23]
# typos #
## The level ##
  
  * in the level read -> in the level reader (missing 'er')

## The list of states ##

  * it something I tweak along -> it is something I tweak along. (verb 'is' missing)
  * We can tem add the code -> Then, we can add the code (them -> then)
  * to the state lists -> to the states list  (misplaced s)
  
 
# Suggestions #

## The Level ##

The first sentence is maybe too long. I find it difficult to understand.

In the first sentence, when referencing the first part, maybe add a link to it.

## global ##

Would it be better to express what the elements of code are doing in the present tense? Example:

> First the `level` contains data related to a a game level...

> the the `State` represents a state of the game being solved.

I think that it makes the project more real. Like it's not only an idea but a real thing.

**Comment by archiloque** [comment]
Thanks!
